# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_os = "almalinux/8"

Vagrant.configure("2") do |config|
  config.vm.define "head" do |head|
    head.vm.box = vm_os
    head.vm.network "private_network", ip: "10.255.0.10"
    head.vm.synced_folder ".", "/vagrant", disabled: true

    head.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end

    head.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/head.yml"
      ansible.compatibility_mode = "2.0"
    end
  end

  config.vm.define "node" do |node|
    node.vm.box = vm_os
    node.vm.network "private_network", ip: "10.255.0.11"
    node.vm.synced_folder ".", "/vagrant", disabled: true

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/node.yml"
      ansible.compatibility_mode = "2.0"
    end
  end
end
